name: petfindernetwork
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # firebase
  cupertino_icons: ^1.0.3
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  firebase_messaging:

  # utils
  timeago: ^3.1.0
  provider: ^6.0.5
  image_picker: ^1.0.2
  another_flushbar: ^1.10.24
  cached_network_image: ^3.1.0
  flutter_local_notifications: ^16.3.2
  connectivity: ^3.0.6
  # google_mobile_ads: ^3.0.0
  path: ^1.8.2
#  velocity_x: ^4.1.1
  image_compare_slider: ^2.8.0
  flutter_timezone: ^1.0.8
  image_cropper: ^5.0.1

  # UIUX
  sizer: ^2.0.15
  flutter_admin_scaffold: ^1.2.0
  flutter_spinkit: ^5.1.0
  shimmer: ^3.0.0
  memoize: ^3.0.0
  rxdart: ^0.27.7
  modal_progress_hud_nsn: ^0.4.0
  carousel_slider: ^4.2.1
  ff_navigation_bar_plus: ^0.1.5
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.10
  country_code_picker: ^3.0.0
  geolocator: ^10.0.1
  modal_bottom_sheet: ^2.1.2
  date_time_format: ^2.0.1
  flutter_datetime_picker_plus: ^2.1.0
  geocoding: ^2.1.1
  firebase_app_check: ^0.2.1+8
  firebase_crashlytics: ^3.4.16
  firebase_analytics: ^10.8.7
  easy_sidemenu: ^0.6.0
  # http: ^0.12.0+4
  # ff_navigation_bar: 0.1.5


dev_dependencies:
  #flutter_lints: ^2.0.2
  build_runner: ^2.1.4
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/csv/worldcities.csv

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
